# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ea091782dd76bf7345ba88262be7bb2a53595ef658046bf02da78fcec49fe06f866ab34c57b7736ba041d56a199566dc676980fe630b3ef3a1e8a7e9699e5f

test:
  secret_key_base: f55fbc5a94e0155f815e6f329425c2ee2058f90e2b47a316c71b11f488ade0c6ee9599761ab1f13658a3e3fa799b560912384775d87d152f4eba3846edc6cafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
